version: '3.5'

services:
  app:
    container_name: task-tracker
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATA_URL: jdbc:postgresql://db:5432/task-manager-db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: ttdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task-manager-db
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task-manager-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mail.ru
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8081:8081"
volumes:
  db:
  pgadmin: