spring:
  application:
    name: TaskTrackerBackend
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/changelog/changelog.yml
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
          auth: true

jwt:
  secret: ${SECURITY_TOKEN_SECRET}
  expiration: ${SECURITY_TOKEN_LIFETIME}

frontend:
  enabled: true
  url: ${FRONTEND_URL}
  oauth-callback: ${FRONTEND_OAUTH_CALLBACK}

